service: survey-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  apiKeys:
    - ${self:service}-${opt:stage, self:provider.stage}
  runtime: nodejs4.3
  stage: ${env:SLS_STAGE,dev}
  region: ${env:SLS_REGION,eu-west-1}
  profile: ${env:SLS_PROFILE}
  memorySize : 128
  versionFunctions: false
  environment:
    SURVEYS_TABLE: survey-api-surveys-${opt:stage, self:provider.stage}
    QUESTION_SETS_TABLE: survey-api-question-sets-${opt:stage, self:provider.stage}
    RESPONSES_TABLE: survey-api-responses-${opt:stage, self:provider.stage}
  iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/survey-api-*"

functions:
  createSurvey:
      handler: surveys/create.create
      events:
        - http:
            path: surveys
            method: post
            cors: true
            private: true

  getSurvey:
      handler: surveys/get.get
      events:
        - http:
            path: surveys/{id}
            method: get
            cors: true
            private: true

  updateSurvey:
      handler: surveys/update.update
      events:
        - http:
            path: surveys/{id}
            method: put
            cors: true
            private: true

  deleteSurvey:
      handler: surveys/delete.delete
      events:
        - http:
            path: surveys/{id}
            method: delete
            cors: true
            private: true

  listSurveys:
      handler: surveys/list.list
      events:
      - http:
          path: surveys
          method: get
          cors: true
          private: true

  createQuestionSet:
      handler: questionSets/create.create
      events:
      - http:
          path: question-sets
          method: post
          cors: true
          private: true

  createResponse:
      handler: responses/create.create
      events:
      - http:
          path: responses
          method: post
          cors: true
          private: true

resources:
  Resources:
    surveysTable:
      Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      Properties:
          TableName: ${self:provider.environment.SURVEYS_TABLE}
          AttributeDefinitions:
            - AttributeName: surveyId
              AttributeType: N
          KeySchema:
            - AttributeName: surveyId
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

    questionSetsTable:
        Type: AWS::DynamoDB::Table
        # DeletionPolicy: Retain
        Properties:
          TableName: ${self:provider.environment.QUESTION_SETS_TABLE}
          AttributeDefinitions:
            - AttributeName: surveyId
              AttributeType : N
          KeySchema:
            - AttributeName: surveyId
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

    responsesTable:
        Type: AWS::DynamoDB::Table
        # DeletionPolicy: Retain
        Properties:
          TableName: ${self:provider.environment.RESPONSES_TABLE}
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: N
            - AttributeName: surveyId
              AttributeType: N
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: surveyId
              KeyType: RANGE
          ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
