service: survey-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  apiKeys:
    - ${self:service}-${opt:stage, self:provider.stage}
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1
  profile: PaoloT-cli
  memorySize : 128
  versionFunctions: false
  iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/survey-api-table"

functions:
  create:
      handler: surveys/create.create
      events:
        - http:
            path: surveys
            method: post
            cors: true
            private: true

  get:
      handler: surveys/get.get
      events:
        - http:
            path: surveys/{id}
            method: get
            cors: true
            private: true

  update:
      handler: surveys/update.update
      events:
        - http:
            path: surveys/{id}
            method: put
            cors: true
            private: true

  delete:
      handler: surveys/delete.delete
      events:
        - http:
            path: surveys/{id}
            method: delete
            cors: true
            private: true

  list:
      handler: surveys/list.list
      events:
      - http:
          path: surveys
          method: get
          cors: true
          private: true

resources:
  Resources:
    surveysTable:
      Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      Properties:
          TableName: survey-api-table
          AttributeDefinitions:
              - AttributeName: id
                AttributeType : N
          KeySchema:
              - AttributeName: id
                KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
